import Link from 'next/link';
import { agentes } from '../lib/agentes';
import { Badge, ButtonLink, Card, Container, Section, SectionTitle } from './components/ui';

const processo=[['01','Diagnóstico','Mapeamos empresa, oferta, dúvidas, regras e objetivos.'],['02','Treinamento','Criamos prompt, base de conhecimento e fluxos do agente exclusivo.'],['03','Ativação','Conectamos o agente ao ambiente de chat e validamos respostas.'],['04','Otimização','Acompanhamos leads, conversas e melhorias contínuas.']];
const comparacao=[['Primeiro atendimento','Demora e perde oportunidade','Resposta imediata 24h'],['Padrão de resposta','Cada pessoa responde de um jeito','Linguagem alinhada à marca'],['Leads','Ficam espalhados em chats','São capturados e qualificados'],['Escala','Depende de contratar mais pessoas','Atende vários clientes ao mesmo tempo']];
const faqs=[['Posso testar antes de contratar?','Sim. A página de demo mostra o comportamento comercial de cada tipo de agente antes do pré-cadastro.'],['O agente é exclusivo?','Sim. Cada empresa tem agente, prompt, documentos e configurações próprios.'],['Preciso saber programação?','Não. O objetivo é a empresa usar tudo por uma interface simples.'],['Serve para pequenas empresas?','Sim. A Agentes AI foi estruturada para começar simples e evoluir conforme o negócio cresce.'],['Já tem área da empresa?','Sim. Clientes autorizados acessam um painel para acompanhar agentes, conversas, documentos e configurações da operação.']];

export default function Home(){ const destaques=agentes.filter(a=>a.destaque).slice(0,4); return <main className="pt-20">
  <section className="hero-bg relative overflow-hidden"><div className="absolute inset-0 grid-bg opacity-40"/><Container className="relative py-24 sm:py-32 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center">
    <div><Badge>Agentes exclusivos para empresas</Badge><h1 className="mt-6 text-4xl sm:text-6xl lg:text-7xl font-black leading-[1.02] tracking-tight">Venda, atenda e automatize com um <span className="text-gradient-main">agente próprio</span> no chat.</h1><p className="mt-6 text-lg sm:text-xl text-slate-300 leading-relaxed max-w-2xl">A Agentes AI cria agentes de IA treinados para cada empresa: com linguagem, regras, documentos, histórico e objetivos próprios.</p><div className="mt-8 flex flex-col sm:flex-row gap-4"><ButtonLink href="/pre-cadastro">Solicitar diagnóstico</ButtonLink><ButtonLink href="/agentes" variant="outline">Ver catálogo</ButtonLink><ButtonLink href="/demo" variant="outline">Testar demo</ButtonLink></div><div className="mt-8 grid grid-cols-3 gap-3 max-w-xl">{[['24h','online'],['1:1','por empresa'],['8','agentes base']].map(([n,l])=><Card key={l} className="text-center p-4"><div className="text-3xl font-black">{n}</div><div className="text-xs uppercase tracking-widest text-slate-500 font-bold">{l}</div></Card>)}</div></div>
    <Card className="p-5 sm:p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="font-black text-xl">Agente de Vendas</h2><p className="text-sm text-slate-500">Empresa: Clínica Exemplo</p></div><span className="rounded-full bg-green-500/10 text-green-300 px-3 py-1 text-xs font-bold">Online</span></div><div className="space-y-4 rounded-3xl bg-black/25 p-4 border border-white/10"><Bubble who="Cliente">Vocês atendem amanhã depois das 18h?</Bubble><Bubble who="Agentes AI" right>Sim. Tenho disponibilidade às 18h30 e 19h. Posso reservar e enviar confirmação?</Bubble><div className="grid grid-cols-2 gap-3 pt-2">{['Lead capturado','Agenda consultada','Resposta aprovada','Próxima ação'].map(x=><div className="rounded-2xl bg-white/5 border border-white/10 p-3 text-xs text-slate-400 font-bold" key={x}>● {x}</div>)}</div></div></Card>
  </Container></section>
  <Section><Container><SectionTitle eyebrow="Site que vende" title="Uma estrutura comercial para transformar visitantes em empresas interessadas." desc="A página apresenta problema, solução, catálogo, planos, prova de valor e CTA em uma jornada clara."/><div className="grid md:grid-cols-4 gap-4">{['Atendimento 24h','Mais leads qualificados','Menos trabalho manual','Agente exclusivo'].map(t=><Card key={t}><h3 className="font-black text-xl mb-2">{t}</h3><p className="text-slate-400 text-sm leading-relaxed">Benefício direto para empresas que dependem de velocidade e consistência no atendimento.</p></Card>)}</div></Container></Section>
  <Section className="bg-black/20"><Container><SectionTitle eyebrow="Catálogo" title="Agentes prontos para vender, atender e organizar processos." desc="Cada agente pode virar uma página própria, plano comercial e fluxo de implantação."/><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">{destaques.map(a=><Link href={`/agentes/${a.slug}`} key={a.slug} className="card rounded-3xl p-6 no-underline"><div className="w-12 h-12 rounded-2xl bg-red-500/10 border border-red-500/20 flex items-center justify-center font-black text-red-200 mb-5">{a.icon}</div><h3 className="font-black text-xl mb-2">{a.nome}</h3><p className="text-sm text-slate-400 leading-relaxed mb-5">{a.descricao}</p><div className="text-red-300 font-black">R$ {a.preco}/mês →</div></Link>)}</div></Container></Section>
  <Section><Container><SectionTitle eyebrow="Como funciona" title="Processo simples para implantar com segurança."/><div className="grid md:grid-cols-4 gap-4">{processo.map(([n,t,d])=><Card key={n}><div className="text-red-300 font-black mb-4">{n}</div><h3 className="font-black text-xl mb-2">{t}</h3><p className="text-sm text-slate-400 leading-relaxed">{d}</p></Card>)}</div></Container></Section>
  <Section className="bg-black/20"><Container><SectionTitle eyebrow="Comparação" title="Sem IA vs com Agentes AI."/><div className="space-y-3">{comparacao.map(r=><div className="table-row" key={r[0]}><div className="font-black text-white">{r[0]}</div><div className="text-slate-500">{r[1]}</div><div className="text-green-300 font-semibold">{r[2]}</div></div>)}</div></Container></Section>
  <Section><Container><div className="grid lg:grid-cols-2 gap-10 items-center"><SectionTitle align="left" eyebrow="Próximo passo" title="Comece com pré-cadastro comercial." desc="O formulário coleta as informações necessárias para entender empresa, segmento, agente desejado e principal problema."/><Card><h3 className="font-black text-2xl mb-4">O que será capturado</h3><ul className="space-y-3 text-slate-300">{['Nome, empresa e WhatsApp','Segmento e tamanho da empresa','Tipo de agente desejado','Principal problema operacional'].map(i=><li key={i}>✓ {i}</li>)}</ul><ButtonLink href="/pre-cadastro" className="mt-6 block">Fazer pré-cadastro</ButtonLink></Card></div></Container></Section>
  <Section className="bg-black/20"><Container><SectionTitle eyebrow="FAQ" title="Dúvidas frequentes."/><div className="grid md:grid-cols-2 gap-5">{faqs.map(([q,a])=><Card key={q}><h3 className="font-black text-lg mb-2">{q}</h3><p className="text-slate-400 leading-relaxed">{a}</p></Card>)}</div></Container></Section>
</main> }
function Bubble({children,right}){return <div className={`flex ${right?'justify-end':''}`}><div className={`${right?'bg-red-500/15 border-red-500/20':'bg-white/5 border-white/10'} border rounded-2xl p-3 max-w-[82%] text-sm text-slate-200`}>{children}</div></div>}
