export const agentes = [
  { slug:'atendimento', nome:'Agente de Atendimento', categoria:'Atendimento', icon:'OC', descricao:'Responde dúvidas frequentes, identifica necessidade do cliente e encaminha casos importantes para humano.', paraQuem:'Clínicas, lojas, escolas, academias e empresas com grande volume de perguntas repetidas.', precoAtivacao:297, preco:197, destaque:true, beneficios:['Atendimento 24h com respostas padronizadas','Redução de filas no WhatsApp e Instagram','Triagem automática antes do atendimento humano','Base de conhecimento exclusiva da empresa'], funcionalidades:['FAQ inteligente','Captura de dados do cliente','Escalação para humano','Resumo de atendimento','Tom de voz configurável'] },
  { slug:'vendas', nome:'Agente de Vendas', categoria:'Comercial', icon:'VD', descricao:'Qualifica leads, apresenta produtos, responde objeções e conduz o cliente até a próxima etapa de compra.', paraQuem:'Empresas que recebem interessados pelo WhatsApp, Instagram, site ou campanhas pagas.', precoAtivacao:497, preco:297, destaque:true, beneficios:['Mais velocidade no primeiro contato','Qualificação de oportunidades','Respostas consistentes sobre preço e oferta','Encaminhamento para fechamento'], funcionalidades:['Roteiro comercial','Perguntas de qualificação','Objeções e argumentos','Registro de lead','CTA para vendedor'] },
  { slug:'suporte', nome:'Agente de Suporte', categoria:'Suporte', icon:'SP', descricao:'Ajuda clientes no pós-venda, orienta sobre uso, abre chamados e reduz carga operacional da equipe.', paraQuem:'SaaS, lojas, serviços recorrentes, infoprodutos e operações com suporte repetitivo.', precoAtivacao:397, preco:247, destaque:false, beneficios:['Menos tickets repetitivos','Respostas rápidas no pós-venda','Histórico organizado','Melhor experiência do cliente'], funcionalidades:['Base de ajuda','Classificação de prioridade','Abertura de ticket','Escalação','Resumo do problema'] },
  { slug:'agendamento', nome:'Agente de Agendamento', categoria:'Agenda', icon:'AG', descricao:'Marca, confirma, remarca e cancela horários seguindo as regras de agenda da empresa.', paraQuem:'Clínicas, salões, barbearias, consultórios, estética, aulas e serviços com horário marcado.', precoAtivacao:497, preco:297, destaque:true, beneficios:['Menos faltas e esquecimentos','Confirmação automática','Organização de horários','Atendimento fora do expediente'], funcionalidades:['Coleta de dados','Regras de agenda','Confirmação','Reagendamento','Lembretes'] },
  { slug:'financeiro', nome:'Agente Financeiro', categoria:'Financeiro', icon:'FN', descricao:'Responde dúvidas de pagamento, orienta sobre cobranças, envia instruções e organiza solicitações financeiras.', paraQuem:'Empresas com boletos, mensalidades, cobranças recorrentes ou dúvidas frequentes de pagamento.', precoAtivacao:597, preco:347, destaque:false, beneficios:['Menos trabalho manual no financeiro','Respostas padronizadas sobre cobrança','Organização de solicitações','Redução de dúvidas repetidas'], funcionalidades:['Status de pagamento','Orientações de cobrança','Segunda via','Registro de solicitação','Encaminhamento seguro'] },
  { slug:'cobranca', nome:'Agente de Cobrança', categoria:'Cobrança', icon:'CB', descricao:'Faz lembretes educados, organiza pendências e conduz negociações simples com linguagem profissional.', paraQuem:'Escolas, academias, clínicas, prestadores de serviço e negócios com pagamentos recorrentes.', precoAtivacao:597, preco:347, destaque:false, beneficios:['Cobrança mais organizada','Menos constrangimento operacional','Follow-up automático','Mensagens padronizadas'], funcionalidades:['Lembretes','Negociação simples','Registro de promessa','Escalação','Relatório'] },
  { slug:'social-media', nome:'Agente de Social Media', categoria:'Marketing', icon:'SM', descricao:'Cria ideias de conteúdo, organiza calendário editorial e responde demandas simples de marketing.', paraQuem:'Empresas que precisam manter presença digital com consistência e menos esforço operacional.', precoAtivacao:397, preco:247, destaque:false, beneficios:['Mais consistência de conteúdo','Ideias alinhadas ao negócio','Calendário organizado','Menos bloqueio criativo'], funcionalidades:['Ideias de posts','Calendário','Legendas','Briefings','Respostas de DM'] },
  { slug:'juridico', nome:'Agente Jurídico', categoria:'Operacional', icon:'JR', descricao:'Organiza triagem inicial, coleta informações e orienta próximos passos administrativos com limites bem definidos.', paraQuem:'Escritórios e departamentos que precisam coletar dados iniciais sem substituir análise profissional.', precoAtivacao:797, preco:497, destaque:false, beneficios:['Triagem inicial eficiente','Coleta estruturada de dados','Encaminhamento para responsável','Padronização do primeiro atendimento'], funcionalidades:['Perguntas de triagem','Checklist','Classificação','Resumo','Encaminhamento'] },
];

export const planos = [
  { nome:'Start', preco:'197', descricao:'Para validar o primeiro agente.', recursos:['1 agente exclusivo','Base de conhecimento inicial','Chat web','Suporte padrão','Relatório básico'], cta:'Começar no Start' },
  { nome:'Pro', preco:'397', destaque:true, descricao:'Para empresas que querem vender e atender melhor.', recursos:['Até 3 agentes','Fluxos comerciais','Formulários de lead','Suporte prioritário','Ajustes mensais'], cta:'Escolher Pro' },
  { nome:'Business', preco:'797', descricao:'Para operações com mais volume e processos.', recursos:['Até 8 agentes','Dashboard da empresa','Integrações planejadas','Relatórios avançados','Treinamento guiado'], cta:'Falar sobre Business' },
  { nome:'Enterprise', preco:'Sob consulta', descricao:'Para projetos personalizados e escala.', recursos:['Agentes ilimitados sob contrato','Multiempresa avançado','White label','SLA e implantação dedicada','Integrações sob medida'], cta:'Solicitar proposta' },
];

export function getAgente(slug){ return agentes.find(a=>a.slug===slug); }
