export const categorias = [
  'Todos',
  'Atendimento',
  'Comercial',
  'Suporte',
  'Agenda',
  'Financeiro',
  'Marketing',
  'Operacional',
];

export const agentes = [
  {
    slug: 'atendimento',
    nome: 'Agente de Atendimento',
    categoria: 'Atendimento',
    icon: 'AT',
    tag: 'Mais procurado',
    nivel: 'Essencial',
    tempoImplantacao: '3 a 7 dias',
    idealPara: ['Clínicas', 'Lojas', 'Escolas', 'Academias'],
    descricao: 'Responde dúvidas frequentes, identifica a necessidade do cliente e encaminha casos importantes para atendimento humano.',
    resumo: 'Primeira linha de atendimento para empresas que recebem muitas perguntas repetidas todos os dias.',
    problema: 'Sua equipe perde tempo respondendo as mesmas dúvidas e o cliente espera demais para receber uma resposta simples.',
    resultado: 'Atendimento imediato, padronizado e disponível fora do horário comercial, sem perder o controle humano nos casos importantes.',
    paraQuem: 'Clínicas, lojas, escolas, academias e empresas com grande volume de perguntas repetidas pelo WhatsApp, Instagram ou site.',
    precoAtivacao: 297,
    preco: 197,
    destaque: true,
    beneficios: [
      'Atendimento 24h com respostas padronizadas',
      'Redução de filas no WhatsApp e Instagram',
      'Triagem automática antes do atendimento humano',
      'Base de conhecimento exclusiva da empresa',
    ],
    funcionalidades: ['FAQ inteligente', 'Captura de dados do cliente', 'Escalação para humano', 'Resumo de atendimento', 'Tom de voz configurável'],
    conversa: [
      ['Cliente', 'Vocês atendem hoje?'],
      ['Agente', 'Sim. Para te ajudar melhor, você procura atendimento presencial ou online?'],
      ['Cliente', 'Presencial. Quero saber valores.'],
      ['Agente', 'Claro. Posso te explicar as opções e coletar seu WhatsApp para a equipe confirmar a melhor condição.'],
    ],
    faq: [
      ['Ele substitui minha equipe?', 'Não. Ele reduz perguntas repetidas e encaminha casos sensíveis para a equipe humana.'],
      ['Posso mudar as respostas?', 'Sim. O tom, regras e base de conhecimento podem ser ajustados conforme a empresa.'],
    ],
  },
  {
    slug: 'vendas',
    nome: 'Agente de Vendas',
    categoria: 'Comercial',
    icon: 'VD',
    tag: 'Alta conversão',
    nivel: 'Crescimento',
    tempoImplantacao: '5 a 10 dias',
    idealPara: ['E-commerce', 'Infoprodutos', 'Serviços', 'Franquias'],
    descricao: 'Qualifica leads, apresenta ofertas, responde objeções e conduz o cliente até a próxima etapa de compra.',
    resumo: 'Agente comercial para responder rápido, qualificar interessados e não deixar leads esfriarem.',
    problema: 'Leads chegam pelo anúncio ou WhatsApp, mas demoram a ser atendidos e acabam comprando da concorrência.',
    resultado: 'Primeiro contato imediato, perguntas de qualificação, argumentos comerciais e encaminhamento para fechamento.',
    paraQuem: 'Empresas que recebem interessados pelo WhatsApp, Instagram, site, tráfego pago ou campanhas comerciais.',
    precoAtivacao: 497,
    preco: 297,
    destaque: true,
    beneficios: ['Mais velocidade no primeiro contato', 'Qualificação de oportunidades', 'Respostas consistentes sobre preço e oferta', 'Encaminhamento para fechamento'],
    funcionalidades: ['Roteiro comercial', 'Perguntas de qualificação', 'Objeções e argumentos', 'Registro de lead', 'CTA para vendedor'],
    conversa: [
      ['Cliente', 'Quanto custa o plano?'],
      ['Agente', 'Depende do seu objetivo. Você quer automatizar atendimento, vendas ou suporte?'],
      ['Cliente', 'Vendas pelo WhatsApp.'],
      ['Agente', 'Perfeito. O plano Pro costuma ser o melhor para isso. Posso coletar alguns dados e te enviar uma proposta?'],
    ],
    faq: [
      ['Ele fecha venda sozinho?', 'Ele conduz a conversa, responde objeções e encaminha para fechamento conforme sua estratégia.'],
      ['Funciona com tráfego pago?', 'Sim. Ele é ideal para responder leads que chegam de anúncios com velocidade.'],
    ],
  },
  {
    slug: 'suporte',
    nome: 'Agente de Suporte',
    categoria: 'Suporte',
    icon: 'SP',
    tag: 'Pós-venda',
    nivel: 'Operação',
    tempoImplantacao: '5 a 10 dias',
    idealPara: ['SaaS', 'Cursos', 'Lojas', 'Serviços recorrentes'],
    descricao: 'Ajuda clientes no pós-venda, orienta sobre uso, abre chamados e reduz carga operacional da equipe.',
    resumo: 'Suporte guiado para reduzir tickets repetitivos e organizar solicitações importantes.',
    problema: 'A equipe responde sempre os mesmos problemas, perde histórico e demora a priorizar casos importantes.',
    resultado: 'Clientes recebem orientação rápida, chamados são classificados e a equipe recebe contexto antes de atuar.',
    paraQuem: 'SaaS, lojas, serviços recorrentes, infoprodutos e operações com suporte repetitivo.',
    precoAtivacao: 397,
    preco: 247,
    destaque: false,
    beneficios: ['Menos tickets repetitivos', 'Respostas rápidas no pós-venda', 'Histórico organizado', 'Melhor experiência do cliente'],
    funcionalidades: ['Base de ajuda', 'Classificação de prioridade', 'Abertura de ticket', 'Escalação', 'Resumo do problema'],
    conversa: [['Cliente', 'Não consigo acessar minha conta.'], ['Agente', 'Vou te ajudar. Você pode confirmar o e-mail usado no cadastro?'], ['Cliente', 'Sim, é o mesmo do pagamento.'], ['Agente', 'Perfeito. Vou registrar o caso como acesso e enviar os próximos passos.']],
    faq: [['Ele resolve problemas técnicos?', 'Ele orienta, coleta contexto e escala para humano quando necessário.'], ['Posso criar base de ajuda?', 'Sim. A base pode conter tutoriais, políticas, processos e respostas padrão.']],
  },
  {
    slug: 'agendamento',
    nome: 'Agente de Agendamento',
    categoria: 'Agenda',
    icon: 'AG',
    tag: 'Agenda cheia',
    nivel: 'Conversão',
    tempoImplantacao: '5 a 10 dias',
    idealPara: ['Clínicas', 'Salões', 'Barbearias', 'Consultórios'],
    descricao: 'Marca, confirma, remarca e cancela horários seguindo as regras de agenda da empresa.',
    resumo: 'Agente para transformar conversas em horários marcados com menos esforço manual.',
    problema: 'A empresa perde horários porque demora a responder, esquece confirmações ou organiza agenda manualmente.',
    resultado: 'Mais horários preenchidos, confirmação automática e menos conversas repetidas sobre disponibilidade.',
    paraQuem: 'Clínicas, salões, barbearias, consultórios, estética, aulas e serviços com horário marcado.',
    precoAtivacao: 497,
    preco: 297,
    destaque: true,
    beneficios: ['Menos faltas e esquecimentos', 'Confirmação automática', 'Organização de horários', 'Atendimento fora do expediente'],
    funcionalidades: ['Coleta de dados', 'Regras de agenda', 'Confirmação', 'Reagendamento', 'Lembretes'],
    conversa: [['Cliente', 'Tem horário amanhã?'], ['Agente', 'Tenho algumas opções. Você prefere manhã, tarde ou noite?'], ['Cliente', 'Noite.'], ['Agente', 'Posso reservar 18h30 ou 19h. Qual prefere?']],
    faq: [['Integra com agenda?', 'A primeira versão pode funcionar com fluxo semi-manual. A integração completa entra na etapa técnica.'], ['Ele confirma presença?', 'Sim. Pode enviar lembretes e pedir confirmação conforme o fluxo definido.']],
  },
  {
    slug: 'financeiro',
    nome: 'Agente Financeiro',
    categoria: 'Financeiro',
    icon: 'FN',
    tag: 'Organização',
    nivel: 'Controle',
    tempoImplantacao: '7 a 14 dias',
    idealPara: ['Escolas', 'Academias', 'Serviços', 'Assinaturas'],
    descricao: 'Responde dúvidas de pagamento, orienta sobre cobranças, envia instruções e organiza solicitações financeiras.',
    resumo: 'Atendimento financeiro padronizado para reduzir dúvidas e organizar solicitações.',
    problema: 'Dúvidas sobre pagamento tomam tempo da equipe e chegam sem organização ou contexto.',
    resultado: 'Orientações padronizadas, coleta de dados e encaminhamento seguro para o financeiro.',
    paraQuem: 'Empresas com boletos, mensalidades, cobranças recorrentes ou dúvidas frequentes de pagamento.',
    precoAtivacao: 597,
    preco: 347,
    destaque: false,
    beneficios: ['Menos trabalho manual no financeiro', 'Respostas padronizadas sobre cobrança', 'Organização de solicitações', 'Redução de dúvidas repetidas'],
    funcionalidades: ['Status de pagamento', 'Orientações de cobrança', 'Segunda via', 'Registro de solicitação', 'Encaminhamento seguro'],
    conversa: [['Cliente', 'Quero a segunda via.'], ['Agente', 'Claro. Para localizar, me informe CPF/CNPJ ou código de cliente.'], ['Cliente', 'Posso mandar por aqui?'], ['Agente', 'Sim. Vou registrar a solicitação e encaminhar com segurança para o financeiro.']],
    faq: [['Ele acessa dados bancários?', 'Não sem integração segura. A primeira etapa organiza solicitações e orientações.'], ['Dá para integrar pagamentos?', 'Sim. Mercado Pago, Stripe ou Pix podem entrar na etapa de pagamentos.']],
  },
  {
    slug: 'cobranca',
    nome: 'Agente de Cobrança',
    categoria: 'Financeiro',
    icon: 'CB',
    tag: 'Recorrência',
    nivel: 'Controle',
    tempoImplantacao: '7 a 14 dias',
    idealPara: ['Escolas', 'Academias', 'Clínicas', 'Serviços mensais'],
    descricao: 'Faz lembretes educados, organiza pendências e conduz negociações simples com linguagem profissional.',
    resumo: 'Cobrança com comunicação profissional, registro de retorno e menos desconforto operacional.',
    problema: 'Cobrar manualmente é demorado, desconfortável e muitas vezes não tem follow-up consistente.',
    resultado: 'Lembretes organizados, linguagem padronizada e registro das respostas para acompanhamento.',
    paraQuem: 'Escolas, academias, clínicas, prestadores de serviço e negócios com pagamentos recorrentes.',
    precoAtivacao: 597,
    preco: 347,
    destaque: false,
    beneficios: ['Cobrança mais organizada', 'Menos constrangimento operacional', 'Follow-up automático', 'Mensagens padronizadas'],
    funcionalidades: ['Lembretes', 'Negociação simples', 'Registro de promessa', 'Escalação', 'Relatório'],
    conversa: [['Agente', 'Olá! Passando para lembrar sobre uma pendência em aberto. Posso te enviar as opções de regularização?'], ['Cliente', 'Pode mandar.'], ['Agente', 'Perfeito. Vou registrar seu retorno e enviar as opções disponíveis.']],
    faq: [['A cobrança é agressiva?', 'Não. A linguagem é profissional, educada e definida pela empresa.'], ['Ele negocia valores?', 'Pode seguir regras simples de negociação, sempre com limites configurados.']],
  },
  {
    slug: 'social-media',
    nome: 'Agente de Social Media',
    categoria: 'Marketing',
    icon: 'SM',
    tag: 'Conteúdo',
    nivel: 'Marketing',
    tempoImplantacao: '3 a 7 dias',
    idealPara: ['Negócios locais', 'Criadores', 'Clínicas', 'Prestadores'],
    descricao: 'Cria ideias de conteúdo, organiza calendário editorial e responde demandas simples de marketing.',
    resumo: 'Assistente de conteúdo para manter consistência sem depender de inspiração todos os dias.',
    problema: 'A empresa sabe que precisa postar, mas não tem rotina, pauta ou clareza do que publicar.',
    resultado: 'Calendário organizado, ideias alinhadas ao negócio e apoio na produção de conteúdo.',
    paraQuem: 'Empresas que precisam manter presença digital com consistência e menos esforço operacional.',
    precoAtivacao: 397,
    preco: 247,
    destaque: false,
    beneficios: ['Mais consistência de conteúdo', 'Ideias alinhadas ao negócio', 'Calendário organizado', 'Menos bloqueio criativo'],
    funcionalidades: ['Ideias de posts', 'Calendário', 'Legendas', 'Briefings', 'Respostas de DM'],
    conversa: [['Usuário', 'Preciso de ideias para uma clínica estética.'], ['Agente', 'Posso montar uma semana de conteúdo com posts educativos, prova social e CTA para avaliação.'], ['Usuário', 'Quero vender limpeza de pele.'], ['Agente', 'Perfeito. Vou criar uma sequência com dor, benefício, prova e chamada para agendamento.']],
    faq: [['Ele posta automaticamente?', 'A primeira versão organiza e cria conteúdo. Automação de postagem pode entrar depois.'], ['Ele segue minha identidade?', 'Sim. O tom e temas podem ser configurados por marca.']],
  },
  {
    slug: 'juridico',
    nome: 'Agente Jurídico',
    categoria: 'Operacional',
    icon: 'JR',
    tag: 'Triagem',
    nivel: 'Especializado',
    tempoImplantacao: '7 a 14 dias',
    idealPara: ['Escritórios', 'Departamentos jurídicos', 'Consultorias'],
    descricao: 'Organiza triagem inicial, coleta informações e orienta próximos passos administrativos com limites bem definidos.',
    resumo: 'Triagem administrativa para organizar demandas sem substituir análise profissional.',
    problema: 'Muitas solicitações chegam incompletas e tomam tempo antes mesmo da análise técnica.',
    resultado: 'Coleta inicial padronizada, classificação da demanda e resumo para o responsável.',
    paraQuem: 'Escritórios e departamentos que precisam coletar dados iniciais sem substituir análise profissional.',
    precoAtivacao: 797,
    preco: 497,
    destaque: false,
    beneficios: ['Triagem inicial eficiente', 'Coleta estruturada de dados', 'Encaminhamento para responsável', 'Padronização do primeiro atendimento'],
    funcionalidades: ['Perguntas de triagem', 'Checklist', 'Classificação', 'Resumo', 'Encaminhamento'],
    conversa: [['Cliente', 'Preciso falar sobre contrato.'], ['Agente', 'Posso coletar informações iniciais para direcionar corretamente. É contrato empresarial, locação ou prestação de serviço?'], ['Cliente', 'Prestação de serviço.'], ['Agente', 'Entendi. Vou registrar os dados e encaminhar para análise do responsável.']],
    faq: [['Ele dá parecer jurídico?', 'Não. Ele faz triagem, coleta dados e encaminha. Não substitui profissional habilitado.'], ['É seguro usar?', 'O fluxo deve ser configurado com limites claros e cuidado com dados sensíveis.']],
  },
];

export const planos = [
  {
    nome: 'Start',
    slug: 'start',
    preco: '197',
    descricao: 'Para validar o primeiro agente com baixo risco.',
    melhorPara: 'Negócios pequenos começando com automação.',
    recursos: ['1 agente exclusivo', 'Base de conhecimento inicial', 'Chat web', 'Suporte padrão', 'Relatório básico', 'Ajuste inicial de tom'],
    limites: ['Sem integrações avançadas', 'Sem dashboard completo'],
    cta: 'Começar no Start',
  },
  {
    nome: 'Pro',
    slug: 'pro',
    preco: '397',
    destaque: true,
    descricao: 'Para empresas que querem vender e atender melhor.',
    melhorPara: 'Operações comerciais com leads recorrentes.',
    recursos: ['Até 3 agentes', 'Fluxos comerciais', 'Formulários de lead', 'Suporte prioritário', 'Ajustes mensais', 'Resumo de conversas'],
    limites: ['Integrações sob avaliação'],
    cta: 'Escolher Pro',
  },
  {
    nome: 'Business',
    slug: 'business',
    preco: '797',
    descricao: 'Para operações com mais volume e processos.',
    melhorPara: 'Empresas com atendimento, vendas e suporte.',
    recursos: ['Até 8 agentes', 'Dashboard da empresa', 'Integrações planejadas', 'Relatórios avançados', 'Treinamento guiado', 'Reunião de implantação'],
    limites: ['Customizações grandes sob proposta'],
    cta: 'Falar sobre Business',
  },
  {
    nome: 'Enterprise',
    slug: 'enterprise',
    preco: 'Sob consulta',
    descricao: 'Para projetos personalizados e escala.',
    melhorPara: 'Empresas que precisam de implantação dedicada.',
    recursos: ['Agentes ilimitados sob contrato', 'Multiempresa avançado', 'White label', 'SLA e implantação dedicada', 'Integrações sob medida', 'Acompanhamento estratégico'],
    limites: ['Projeto sob diagnóstico'],
    cta: 'Solicitar proposta',
  },
];

export const comparativoPlanos = [
  ['Agentes inclusos', '1', 'Até 3', 'Até 8', 'Sob contrato'],
  ['Base de conhecimento', 'Inicial', 'Completa', 'Completa + processos', 'Personalizada'],
  ['Dashboard', 'Básico', 'Básico', 'Avançado', 'Customizado'],
  ['Suporte', 'Padrão', 'Prioritário', 'Prioritário + implantação', 'Dedicado'],
  ['Integrações', 'Não incluso', 'Sob avaliação', 'Planejadas', 'Sob medida'],
];

export function getAgente(slug) {
  return agentes.find((a) => a.slug === slug);
}

export function getAgentesByCategoria(categoria) {
  if (!categoria || categoria === 'Todos') return agentes;
  return agentes.filter((a) => a.categoria === categoria);
}
