// Complexidade:
//   simples  → ativação R$20, mensalidade R$50
//   complexo → ativação R$20, mensalidade R$65

export const agentes = [
  {
    slug: 'atendimento',
    nome: 'Agente de Atendimento',
    emoji: '🎧',
    descricao: 'Responde dúvidas, informa horários e resolve problemas sem precisar de funcionário.',
    complexidade: 'simples',
    precoAtivacao: 20,
    preco: 50,
    funcionalidades: [
      'Respostas automáticas 24/7',
      'Informações de horário e endereço',
      'Resolução de dúvidas frequentes',
      'Encaminhamento de casos complexos',
      'Disponível 24h no Telegram',
    ],
  },
  {
    slug: 'calendario',
    nome: 'Agente de Calendário',
    emoji: '🗓️',
    descricao: 'Gerencia sua agenda, eventos e envia lembretes automáticos para sua equipe.',
    complexidade: 'simples',
    precoAtivacao: 20,
    preco: 50,
    funcionalidades: [
      'Gestão de eventos e compromissos',
      'Lembretes automáticos',
      'Organização semanal e mensal',
      'Integração com agenda do negócio',
      'Disponível 24h no Telegram',
    ],
  },
  {
    slug: 'suporte',
    nome: 'Agente de Suporte',
    emoji: '🛠️',
    descricao: 'Resolve problemas pós-venda, acompanha chamados e orienta seus clientes.',
    complexidade: 'simples',
    precoAtivacao: 20,
    preco: 50,
    funcionalidades: [
      'Atendimento pós-venda automático',
      'Acompanhamento de chamados',
      'Instruções de uso detalhadas',
      'Escalada para equipe humana',
      'Disponível 24h no Telegram',
    ],
  },
  {
    slug: 'agendamento',
    nome: 'Agente de Agendamento',
    emoji: '📅',
    descricao: 'Marca, confirma e cancela horários automaticamente. Ideal para clínicas e salões.',
    complexidade: 'complexo',
    precoAtivacao: 20,
    preco: 65,
    funcionalidades: [
      'Marcação de horários automática',
      'Confirmação e cancelamento',
      'Lembretes para clientes',
      'Organização da agenda',
      'Disponível 24h no Telegram',
    ],
  },
  {
    slug: 'vendas',
    nome: 'Agente de Vendas',
    emoji: '💰',
    descricao: 'Qualifica leads, apresenta produtos e converte clientes automaticamente, 24h por dia.',
    complexidade: 'complexo',
    precoAtivacao: 20,
    preco: 65,
    funcionalidades: [
      'Qualificação automática de leads',
      'Apresentação de produtos e preços',
      'Respostas a objeções comuns',
      'Encaminhamento para fechamento',
      'Disponível 24h no Telegram',
    ],
  },
  {
    slug: 'emails',
    nome: 'Agente de Emails',
    emoji: '📧',
    descricao: 'Lê, classifica e responde emails automaticamente com linguagem profissional.',
    complexidade: 'complexo',
    precoAtivacao: 20,
    preco: 65,
    funcionalidades: [
      'Leitura automática de emails',
      'Classificação por prioridade',
      'Respostas profissionais automáticas',
      'Encaminhamento de emails importantes',
      'Relatório diário de emails',
    ],
  },
  {
    slug: 'manutencao',
    nome: 'Agente de Manutenção',
    emoji: '🔧',
    descricao: 'Monitora e corrige seus outros agentes automaticamente. Nunca fica sem suporte.',
    complexidade: 'complexo',
    precoAtivacao: 20,
    preco: 65,
    funcionalidades: [
      'Monitoramento de todos os agentes',
      'Detecção automática de erros',
      'Correção de problemas comuns',
      'Alertas para problemas críticos',
      'Relatório de status diário',
    ],
  },
];
